language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

# command to install dependencies
install:
  - pip install -r stable-req.txt

# command to run tests
script:
  - mypy dns_shark
  - mypy test
  - coverage run -m unittest discover
  - codecov

branches:
  only:
    - master